spring:
  application:
    name: assistant
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
      embedding:
        options:
          model: text-embedding-3-large
    vectorstore:
      chroma:
        initialize-schema: true
        collection-name: solr_in_action
    ollama:
      chat:
        model: llama3.1
      embedding:
        model: mxbai-embed-large
      init:
        pull-model-strategy: when_missing
  docker:
    compose:
      lifecycle-management: start_only
  shell:
    interactive:
      enabled: true
    script:
      enabled: true
  threads:
    virtual:
      enabled: true
  http:
    client:
      read-timeout: 300s
      connect-timeout: 30s
main:
  banner-mode: off
logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: '*'